# Generated by Django 4.0.2 on 2022-02-23 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='EndUser',
        ),
        migrations.AlterModelOptions(
            name='enduser',
            options={'verbose_name': 'EndUser', 'verbose_name_plural': 'EndUsers'},
        ),
    ]
